name: Update and Validate Upstream Scripts

on:
  push:
    branches:
      - upstream
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without creating a pull request"
        required: false
        default: "true"

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  update-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
          ssh-key: ${{ secrets.AUTOMATED_PRANAVMISHRA90_SSHKEY }}
          
      - name: Setup | Force correct release branch on workflow SHA
        run: |
          git checkout -B ${{ github.ref_name }}

      - name: Setup | Configure Git
        run: |
          git config --global user.email "62562712+pranavmishra90@users.noreply.github.com"
          git config --global user.name "Pranav Kumar Mishra"

          if ! ssh-add -l | grep -q "ED25519"; then
            echo "No SSH key found in agent. Trying to restart the ssh-agent."
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.AUTOMATED_PRANAVMISHRA90_SSHKEY }}"
          fi

          if ! ssh-add -l | grep -q "ED25519"; then
            echo "No SSH key found in agent. Disabling commit signing."
            git config --global commit.gpgsign false
          else
            echo "SSH key found in agent. Enabling commit signing."
            git config --global user.signingkey "ssh-ed25519 ${{ secrets.AUTOMATED_PRANAVMISHRA90_SSH_PUBKEY }}  Automated_Signature-Pranav_Mishra"
            git config --global gpg.format ssh
            git config --global commit.gpgsign true
            git config --global tag.gpgSign true
          fi

      - name: Modify script URLs and fix permissions
        shell: bash
        run: ./.github/workflows/scripts/pranavmishra90/mod-upstream-scripts.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.AUTOMATED_PRANAVMISHRA90_SSHKEY }}

      - name: Add a date stamp
        id: date_stamp
        run: |
          DATESTAMP=$(date +%Y-%m-%d)
          echo "timestamp=$DATESTAMP" >> $GITHUB_ENV
          echo "Generated timestamp: $DATESTAMP"

      - name: Dry Run Check
        id: dry_run_check
        run: |
          echo "DRY_RUN=${{ github.event.inputs.dry_run }}" >> $GITHUB_ENV
          echo "Dry run mode is set to: ${{ github.event.inputs.dry_run }}"

      - name: Log Dry-Run Status
        run: |
          echo "Dry run mode is set to: $DRY_RUN"

      - name: Disable Commit Signing
        if: env.DRY_RUN == 'true'
        run: |
          echo "Disabling commit signing for dry run mode."
          git config --global commit.gpgsign false
          git config --global tag.gpgSign true

      - name: Create Pull Request
        id: create_pr
        if: env.DRY_RUN != 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Updated scripts from upstream [${{ env.timestamp }}]"
          body: |
            This PR updates the scripts from the upstream repository.  
            - URLs have been modified to this fork.
            - Permissions have been fixed.

          base: main
          commit-message: "ci: date stamp"
          branch: "feat/update-${{ env.timestamp }}"